import {PDFDocument,StandardFonts,rgb} from "pdf-lib";
import JSZip from "jszip";
import type {BudgetRow} from "./budget-sheet";
import {sheetTotals} from "./budget-sheet";
export async function budgetPdf(name:string,budget:number,rows:BudgetRow[],loadInvoice?:(id:string)=>Promise<{bytes:Uint8Array;type:string}>){
 const pdf=await PDFDocument.create();const font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);let page=pdf.addPage([792,612]),y=566;
 const clean=(s:string)=>Array.from(s.replace(/[\r\n\t]/g," ")).map(c=>{try{font.encodeText(c);return c;}catch{return "?";}}).join("");
 const text=(s:string,x:number,size=10,strong=false)=>page.drawText(clean(s),{x,y,size,font:strong?bold:font,color:rgb(.18,.12,.24)});
 const fit=(s:string,width:number)=>{s=clean(s);while(font.widthOfTextAtSize(s,10)>width)s=s.slice(0,-4)+"...";return s;};
 const cash=(n:number|null)=>n===null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n);
 const totals=sheetTotals(rows);
 function heading(){text("FLEORA  /  EVENT BUDGET",36,12,true);y-=26;text(fit(name,700),36,19,true);y-=24;text(`Budget: ${cash(budget)}    Planned: ${cash(totals.planned)}    Paid: ${cash(totals.paid)}    Due: ${cash(totals.actual-totals.paid)}`,36);y-=20;text("Estimates are included in planned total; amounts without prices are excluded. USD.",36,9);y-=26;["Item / vendor","Estimated","Actual","Paid","Balance"].forEach((s,i)=>text(s,[36,430,520,610,700][i],10,true));y-=20;}
 function room(height=35){if(y<height+36){page=pdf.addPage([792,612]);y=566;heading();}}
 heading();
 for(const category of [...new Set(rows.map(r=>r.category))]){room(80);page.drawRectangle({x:30,y:y-7,width:732,height:24,color:rgb(.94,.91,.97)});text(category,36,12,true);y-=28;const group=rows.filter(r=>r.category===category);
 for(const row of group){room(48);text(fit(row.name,360),36,10,true);[row.estimate,row.actual,row.paid,row.actual===null?null:row.actual-row.paid].forEach((n,i)=>text(cash(n),[430,520,610,700][i],9));y-=14;text(fit(row.vendor,360),36,9);y-=20;}
 const sub=sheetTotals(group);room();text(`${category} subtotal`,36,10,true);[sub.estimate,sub.actual,sub.paid,sub.actual-sub.paid].forEach((n,i)=>text(cash(n),[430,520,610,700][i],9,true));y-=30;}
 room();text("TOTAL",36,11,true);[totals.estimate,totals.actual,totals.paid,totals.actual-totals.paid].forEach((n,i)=>text(cash(n),[430,520,610,700][i],9,true));
 if(loadInvoice){for(const row of rows)for(const invoice of row.invoices){try{const file=await loadInvoice(invoice.id);if(file.type==="application/pdf"||invoice.filename.toLowerCase().endsWith(".pdf")){const source=await PDFDocument.load(file.bytes);for(const p of await pdf.copyPages(source,source.getPageIndices()))pdf.addPage(p);}else{const sharp=(await import("sharp")).default;const png=await sharp(file.bytes,{limitInputPixels:40000000}).rotate().png().toBuffer();const image=await pdf.embedPng(png);const p=pdf.addPage([612,792]);const dim=image.scaleToFit(540,690);p.drawText(clean(`${row.category} / ${invoice.filename}`).slice(0,90),{x:36,y:758,size:10,font});p.drawImage(image,{x:(612-dim.width)/2,y:(730-dim.height)/2,width:dim.width,height:dim.height});}}catch{throw Error(`Could not include invoice “${invoice.filename}”. Try the budget-only PDF or replace this invoice with an unlocked PDF or image.`);}}}
 return pdf.save();
}
const xml=(s:string)=>s.replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
export async function budgetXlsx(name:string,budget:number,rows:BudgetRow[],origin:string,eventId:string){
 const zip=new JSZip();const data:(string|number|null)[][]=[["Fleora event budget",name],["Event budget",budget],["Category","Item / vendor","Vendor / source","Estimated","Actual","Paid","Balance","Invoices"]];
 for(const category of [...new Set(rows.map(r=>r.category))]){const group=rows.filter(r=>r.category===category);for(const r of group)data.push([category,r.name,r.vendor,r.estimate,r.actual,r.paid,r.actual===null?null:r.actual-r.paid,r.invoices.map(i=>`${origin}/events/${eventId}/budget/invoice/${i.id}`).join("\n")]);const s=sheetTotals(group);data.push([category+" subtotal","","",s.estimate,s.actual,s.paid,s.actual-s.paid,""]);}const total=sheetTotals(rows);data.push(["TOTAL","","",total.estimate,total.actual,total.paid,total.actual-total.paid,""]);data.push(["Planned total",total.planned],["Budget remaining",budget-total.planned],["Estimates include DIY items; unknown prices and non-USD products are excluded. Invoice links require sign-in."]);
 const sheet=data.map((row,i)=>`<row r="${i+1}">${row.map((v,j)=>{const ref=String.fromCharCode(65+j)+(i+1);if(v===null)return `<c r="${ref}"/>`;return typeof v==="number"?`<c r="${ref}" s="2"><v>${Number(v.toFixed(2))}</v></c>`:`<c r="${ref}" s="${i<3||String(row[0]).endsWith("subtotal")||row[0]==="TOTAL"?1:0}" t="inlineStr"><is><t xml:space="preserve">${xml(v)}</t></is></c>`;}).join("")}</row>`).join("");
 zip.file("[Content_Types].xml",'<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>');
 zip.file("_rels/.rels",'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');
 zip.file("xl/workbook.xml",'<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Budget" sheetId="1" r:id="rId1"/></sheets></workbook>');
 zip.file("xl/_rels/workbook.xml.rels",'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>');
 zip.file("xl/styles.xml",'<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><color rgb="FF653B83"/><name val="Calibri"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="3"><xf fontId="0" fillId="0" borderId="0" xfId="0"/><xf fontId="1" fillId="0" borderId="0" xfId="0" applyFont="1"/><xf numFmtId="4" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>');
 zip.file("xl/worksheets/sheet1.xml",`<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="3" topLeftCell="A4" state="frozen"/></sheetView></sheetViews><cols><col min="1" max="3" width="30" customWidth="1"/><col min="4" max="7" width="16" customWidth="1"/><col min="8" max="8" width="65" customWidth="1"/></cols><sheetData>${sheet}</sheetData></worksheet>`);
 return zip.generateAsync({type:"uint8array",compression:"DEFLATE"});
}
