import {BUDGET_CATEGORIES,cents} from "./budget";
import {CATEGORIES} from "./constants";
import type {BudgetExpense,BudgetInvoice,Booking,EventPlanItem,EventShoppingItem} from "./types";
export type BudgetRow={id:string;name:string;vendor:string;category:string;estimate:number|null;actual:number|null;paid:number;href?:string;expense?:BudgetExpense;invoices:BudgetInvoice[]};
export function budgetCategory(category:string){if((BUDGET_CATEGORIES as readonly string[]).includes(category))return category;const group=CATEGORIES.find(c=>c.key===category)?.group;return ({decor:"Décor",food:"Food & drink",dessert:"Food & drink",media:"Services",entertainment:"Entertainment",rentals:"Rentals",venue:"Venue",services:"Services",food_drinks:"Food & drink",venue_logistics:"Rentals"} as Record<string,string>)[group??category]??"Other";}
export function buildBudgetRows(expenses:BudgetExpense[],bookings:Booking[],invoices:BudgetInvoice[],names:Map<string,string>,plans:EventPlanItem[],shopping:EventShoppingItem[],eventId:string):BudgetRow[]{
 const rows:BudgetRow[]=[...expenses.map(e=>({id:e.id,name:e.description,vendor:e.vendor_name,category:budgetCategory(e.category),estimate:null,actual:Number(e.amount),paid:Number(e.paid_amount),expense:e,invoices:invoices.filter(i=>i.expense_id===e.id)})),...bookings.filter(b=>b.status!=="cancelled").map(b=>({id:b.id,name:names.get(b.vendor_id)??"Vendor booking",vendor:"Fleora booking",category:budgetCategory(b.category),estimate:null,actual:Number(b.total),paid:Math.max(0,Number(b.total)-Math.max(0,Number(b.balance))),href:`/quotes/${b.quote_id}`,invoices:invoices.filter(i=>i.booking_id===b.id)}))];
 for(const p of plans.filter(p=>p.choice==="diy")){const products=Array.isArray(p.diy_products)?p.diy_products:[];for(const [index,product] of products.entries()){if(!product||product.currency!=="USD")continue;const n=Number(product.price);rows.push({id:`diy:${p.id}:${index}`,name:product.name||p.label,vendor:product.retailer||`${p.label} · DIY`,category:budgetCategory(p.chapter),estimate:product.price!==""&&Number.isFinite(n)?cents(n)*product.quantity/100:null,actual:null,paid:0,href:`/events/${eventId}/diy`,invoices:[]});}}
 for(const item of shopping){rows.push({id:item.id,name:item.name,vendor:item.quantity?`Quantity: ${item.quantity}`:"Shopping",category:budgetCategory(item.source_chapter??item.category),estimate:!item.purchased&&Number(item.paid_amount??0)===0?item.total_cost:null,actual:item.purchased||Number(item.paid_amount??0)>0?item.total_cost:null,paid:Number(item.paid_amount??0),href:item.source_key?`/events/${eventId}/budget?shopping=${item.id}`:`/events/${eventId}/plan/food-drinks`,invoices:[]});}
 return rows.sort((a,b)=>BUDGET_CATEGORIES.indexOf(a.category as typeof BUDGET_CATEGORIES[number])-BUDGET_CATEGORIES.indexOf(b.category as typeof BUDGET_CATEGORIES[number])||a.name.localeCompare(b.name));
}
export function sheetTotals(rows:BudgetRow[]){const t=rows.reduce((t,r)=>({estimate:t.estimate+cents(r.estimate??0),actual:t.actual+cents(r.actual??0),paid:t.paid+cents(r.paid),planned:t.planned+cents(r.actual??r.estimate??0)}),{estimate:0,actual:0,paid:0,planned:0});return {estimate:t.estimate/100,actual:t.actual/100,paid:t.paid/100,planned:t.planned/100};}
