const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText,f);
const {buildBudgetRows,sheetTotals}=require('../src/lib/budget-sheet.ts');const {budgetPdf,budgetXlsx}=require('../src/lib/budget-export.ts');const {PDFDocument}=require('pdf-lib');const JSZip=require('jszip');
const expense={id:'e',description:'Flowers',vendor_name:'Florist',category:'Décor',amount:200.10,paid_amount:50.10};const booking={id:'b',vendor_id:'v',category:'catering',total:300,balance:200,status:'confirmed',quote_id:'q'};
const plans=[{id:'p',chapter:'decor',label:'Balloons',choice:'diy',diy_products:[{name:'Balloons',quantity:3,price:'10.10',currency:'USD'},{name:'Foreign',quantity:1,price:'20',currency:'EUR'}]}];const shopping=[{id:'s',name:'Napkins',source_chapter:'decor',quantity:'2 packs',total_cost:12.20,paid_amount:0,purchased:false}];
const rows=buildBudgetRows([expense],[booking,{...booking,id:'c',status:'cancelled'}],[],new Map([['v','Caterer']]),plans,shopping,'event');
test('DIY estimates stay separate from actual expenses and cancelled/non-USD items',()=>{assert.equal(rows.length,4);assert.deepEqual(sheetTotals(rows),{estimate:42.5,actual:500.1,paid:150.1,planned:542.6});assert.equal(rows.filter(r=>r.category==='Décor').length,3);});
test('purchased shopping does not imply paid and replaces its estimate',()=>{const r=buildBudgetRows([],[],[],new Map(),[],[{...shopping[0],purchased:true}],'event');assert.deepEqual(sheetTotals(r),{estimate:0,actual:12.2,paid:0,planned:12.2});});
test('Excel is a workbook with text-safe names and persistent invoice links',async()=>{const bytes=await budgetXlsx('Birthday',1000,[{...rows[0],name:'=1+1',invoices:[{id:'invoice'}]}],'https://fleoraevents.com','event');const zip=await JSZip.loadAsync(bytes);const xml=await zip.file('xl/worksheets/sheet1.xml').async('string');assert.match(xml,/t="inlineStr"/);assert.match(xml,/=1\+1/);assert.doesNotMatch(xml,/<f>/);assert.match(xml,/budget\/invoice\/invoice/);fs.mkdirSync('../export-qa',{recursive:true});fs.writeFileSync('../export-qa/budget.xlsx',bytes);});
test('PDF paginates and appends all invoice pages in category order',async()=>{const source=await PDFDocument.create();source.addPage();source.addPage();const calls=[];const many=Array.from({length:45},(_,i)=>({...rows[i%rows.length],id:String(i),name:'Event item with accents Décor '+i,invoices:i<2?[{id:String(i),filename:'invoice.pdf'}]:[]}));const pdf=await budgetPdf('Test celebration',1000,many,async id=>{calls.push(id);return {bytes:await source.save(),type:'application/pdf'}});assert.deepEqual(calls,['0','1']);assert.ok((await PDFDocument.load(pdf)).getPageCount()>=7);fs.mkdirSync('../export-qa',{recursive:true});fs.writeFileSync('../export-qa/budget.pdf',pdf);});
test('unreadable invoices stop combined export',async()=>{await assert.rejects(budgetPdf('Test',100,[{...rows[0],invoices:[{id:'bad',filename:'bad.pdf'}]}],async()=>({bytes:new Uint8Array([1,2]),type:'application/pdf'})),/Could not include invoice/);});

test('WebP invoice is converted and appended to PDF',async()=>{const image=await require('sharp')({create:{width:20,height:30,channels:3,background:'#ffffff'}}).webp().toBuffer();const pdf=await budgetPdf('Test',100,[{...rows[0],invoices:[{id:'webp',filename:'invoice.webp'}]}],async()=>({bytes:image,type:'image/webp'}));assert.equal((await PDFDocument.load(pdf)).getPageCount(),2);});
