import Link from "next/link";
import {notFound} from "next/navigation";
import {requireProfile} from "@/lib/auth";
import {createClient} from "@/lib/supabase/server";
import {Card,Progress,Badge} from "@/components/ui";
import {EventWorkspaceHeader} from "@/components/event/event-workspace-header";
import {VENUE_LOGISTICS_PLAN_ITEMS} from "@/lib/planning";
export default async function Page({params}:{params:{id:string}}){await requireProfile();const s=createClient();const {data:event}=await s.from("events").select("*").eq("id",params.id).single();if(!event)notFound();const {data:items}=await s.from("event_plan_items").select("chapter,item_key,choice").eq("event_id",params.id);
function progress(chapter:string,skip:string,group?:string){const all=(items??[]).filter(i=>i.chapter===chapter);if(all.some(i=>i.item_key===skip||chapter==="venue_logistics"&&i.item_key==="no_venue_logistics"))return 1;const rows=all.filter(i=>!i.item_key.startsWith("no_")&&!i.item_key.startsWith("skip_")&&(!group||VENUE_LOGISTICS_PLAN_ITEMS.some(d=>d.key===i.item_key&&d.group===group)));return rows.length?rows.filter(i=>i.choice!=="undecided").length/rows.length:0;}
const chapters=[{title:"Event Details & Vision",desc:"Your date, venue, theme, colors and inspiration.",path:"/edit",value:event.name&&event.event_date?1:0},{title:"Decor",desc:"Backdrops, centerpieces, balloons, signs and finishing touches.",path:"/plan/decor",value:progress("decor","no_decor")},{title:"Rentals",desc:"Tables, chairs, linens, tents, staging and other rental pieces.",path:"/rentals",value:progress("venue_logistics","no_rentals","rentals")},{title:"Food & Drinks",desc:"Meals, cakes, treats, drinks and shared dishes.",path:"/plan/food-drinks",value:progress("food_drinks","skip_food_drinks")},{title:"Services & Entertainment",desc:"Photography, planning, beauty, DJs, performers and activities.",path:"/services-entertainment",value:(progress("services","no_services")+progress("entertainment","no_entertainment"))/2},{title:"Venue & Logistics",desc:"Setup, deliveries, access, parking and event-day details.",path:"/venue-logistics",value:progress("venue_logistics","no_logistics","logistics")}];const pct=Math.round(chapters.reduce((n,c)=>n+c.value,0)/chapters.length*100);
return <div className="space-y-7"><EventWorkspaceHeader event={event} active="/plan" eyebrow="My Party Plan"/><Card variant="feature" className="bg-brand-soft"><p className="fleora-kicker">Dream it → plan it</p><h1 className="mt-2 font-display text-4xl">Build your party, chapter by chapter.</h1><p className="mt-3 text-sm text-ink-600">Choose what to DIY, who to hire, and what you already have. Add tasks and shopping within each category.</p><div className="mt-6"><p className="mb-2 text-sm">{pct}% planned</p><Progress value={pct}/></div></Card><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{chapters.map((c,i)=><Card key={c.title} variant="interactive" className="flex flex-col"><div className="flex justify-between"><p className="fleora-kicker">Chapter {i+1}</p>{c.value===1&&<Badge tone="green">Complete</Badge>}</div><h2 className="mt-4 font-display text-2xl">{c.title}</h2><p className="mt-2 flex-1 text-sm text-ink-600">{c.desc}</p><Link className="mt-5 font-semibold text-plum-700" href={`/events/${event.id}${c.path}`}>{c.value===1?"Edit chapter":"Open chapter"} →</Link></Card>)}</div></div>;}