import Link from "next/link";
import {Card} from "@/components/ui";
import {EventWorkspaceHeader} from "@/components/event/event-workspace-header";
import {BudgetExport} from "@/components/event/budget-export";
import {PlanningList} from "@/components/event/planning-list";
import {loadBudget} from "@/lib/budget-data";
import {sheetTotals} from "@/lib/budget-sheet";
import {money} from "@/lib/format";
import {ExpenseForm,ExpenseControls,RemoveInvoice} from "./expense-form";
export const dynamic="force-dynamic";
export default async function Page({params}:{params:{id:string}}){
 let data;try{data=await loadBudget(params.id);}catch{return <Card><h1 className="font-display text-3xl">Budget unavailable</h1><p className="mt-3">We couldn’t load your complete budget. Please sign in and try again.</p></Card>;}
 const {event,rows,names,bookings,shopping,nonUsd}=data;const totals=sheetTotals(rows);const readerEnabled=Boolean(process.env.OPENAI_API_KEY);const categories=[...new Set(rows.map(r=>r.category))];const remaining=Number(event.budget??0)-totals.planned;
 return <div className="space-y-7"><div className="print:hidden"><EventWorkspaceHeader event={event} active="/budget" eyebrow="Event workspace"/></div><section id="budget-print" className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="fleora-kicker">{event.name}</p><h1 className="font-display text-4xl">Your budget</h1><p className="mt-2 text-sm text-ink-600">Bookings, outside expenses and shopping, together.</p></div><BudgetExport eventId={event.id}/></div>
 <div className="grid grid-cols-2 gap-3 lg:grid-cols-5">{[{label:"Event budget",value:event.budget??0},{label:"Planned total",value:totals.planned},{label:"Paid",value:totals.paid},{label:"Balance due",value:totals.actual-totals.paid},{label:remaining<0?"Over budget":"Budget remaining",value:Math.abs(remaining)}].map(t=><Card key={t.label} className="bg-plum-50/50"><p className="text-xs text-ink-500">{t.label}</p><p className="mt-2 text-xl font-semibold tabular-nums">{money(t.value)}</p></Card>)}</div>
 <p className="text-xs text-ink-500">Planned total includes {money(totals.estimate)} in estimates. Balance due uses confirmed costs only. DIY prices exclude shipping and tax. Items without prices are excluded from totals.</p>{nonUsd>0&&<p role="status" className="text-sm text-amber-800">{nonUsd} DIY item(s) use another currency and are excluded from this USD budget.</p>}
 <div className="overflow-x-auto rounded-2xl border border-plum-100 bg-white"><table className="w-full min-w-[720px] text-left text-sm"><caption className="sr-only">Budget grouped by category</caption><thead className="bg-plum-50 text-xs uppercase tracking-wide text-plum-800"><tr><th className="p-4">Item / vendor</th>{["Estimated","Actual","Paid","Balance"].map(h=><th key={h} className="p-4 text-right">{h}</th>)}<th className="p-4 print:hidden">Invoices & actions</th></tr></thead>{categories.map(category=>{const items=rows.filter(r=>r.category===category),sub=sheetTotals(items);return <tbody key={category} className="break-inside-auto"><tr className="bg-ivory-50"><th colSpan={6} scope="rowgroup" className="px-4 py-3 font-display text-xl text-plum-800">{category}</th></tr>{items.map(row=><tr key={row.id} className="border-t border-plum-50 align-top"><td className="max-w-[280px] p-4"><p className="font-semibold">{row.name}</p><p className="mt-1 text-xs text-ink-500">{row.vendor}</p></td>{[row.estimate,row.actual,row.paid,row.actual===null?null:row.actual-row.paid].map((n,i)=><td key={i} className="p-4 text-right tabular-nums">{n===null?"—":money(n)}</td>)}<td className="max-w-[360px] p-4 print:hidden">{row.invoices.map(i=><div key={i.id} className="mb-2 flex flex-wrap items-center gap-2"><a className="break-all text-plum-700 underline" href={`/events/${event.id}/budget/invoice/${i.id}`} target="_blank" rel="noreferrer">{i.filename}</a><RemoveInvoice eventId={event.id} id={i.id}/></div>)}{row.expense?<ExpenseControls eventId={event.id} expense={row.expense} readerEnabled={readerEnabled}/>:shopping.find(s=>s.id===row.id)?.source_key?<PlanningList eventId={event.id} planKey={shopping.find(s=>s.id===row.id)!.source_key!} label={row.name}/>:row.href?<Link className="text-plum-700 underline" href={row.href}>{row.id.startsWith("diy:")?"Edit / remove shopping item":"Manage item"}</Link>:null}</td></tr>)}<tr className="border-t border-plum-100 bg-plum-50/40 font-semibold"><th className="p-4">{category} subtotal</th>{[sub.estimate,sub.actual,sub.paid,sub.actual-sub.paid].map((n,i)=><td key={i} className="p-4 text-right tabular-nums">{money(n)}</td>)}<td className="print:hidden"/></tr></tbody>})}<tfoot className="bg-plum-100 font-bold"><tr><th className="p-4">Total</th>{[totals.estimate,totals.actual,totals.paid,totals.actual-totals.paid].map((n,i)=><td key={i} className="p-4 text-right tabular-nums">{money(n)}</td>)}<td className="print:hidden"/></tr></tfoot></table>{!rows.length&&<p className="p-6 text-sm text-ink-500">Add your first expense, invoice, or shopping item to start your budget.</p>}</div></section>
 <Card className="print:hidden"><h2 className="mb-4 font-display text-2xl">Add an expense or invoice</h2><ExpenseForm eventId={event.id} readerEnabled={readerEnabled} bookings={bookings.map(b=>({id:b.id,label:names.get(b.vendor_id)??"Vendor booking"}))}/></Card></div>;
}
