"use client";
import {useRef,useState} from "react";
import {createPortal} from "react-dom";
import {useRouter} from "next/navigation";
import {loadPlanningList,savePlanningListItem} from "@/lib/actions/planning-lists";
import {Button,Input} from "@/components/ui";
import type {ChecklistItem,EventShoppingItem} from "@/lib/types";
export function PlanningList({eventId,planKey,label}:{eventId:string;planKey:string;label:string}){
 const dialog=useRef<HTMLDialogElement|null>(null);const [mounted,setMounted]=useState(false);const [data,setData]=useState<{tasks:ChecklistItem[];shopping:EventShoppingItem[]}>({tasks:[],shopping:[]});const [error,setError]=useState("");const [busy,setBusy]=useState(false);const router=useRouter();
 async function refresh(){setData(await loadPlanningList(eventId,planKey));}
 async function save(fd:FormData){setBusy(true);setError("");try{const result=await savePlanningListItem(eventId,planKey,fd);if(result.error)throw Error(result.error);await refresh();router.refresh();return true;}catch(e){setError(e instanceof Error?e.message:"Could not save.");return false;}finally{setBusy(false);}}
 function entry(kind:"task"|"shopping",row?:ChecklistItem|EventShoppingItem){const task=kind==="task";const t=row as ChecklistItem|undefined;const s=row as EventShoppingItem|undefined;return <form key={row?.id??kind} onSubmit={async e=>{e.preventDefault();e.stopPropagation();const form=e.currentTarget;const fd=new FormData(form);if(await save(fd)&&!row)form.reset();}} className="space-y-3 rounded-xl border border-plum-100 p-4">
 <input type="hidden" name="kind" value={kind}/><input type="hidden" name="id" value={row?.id??""}/>
 <label className="block text-xs font-semibold">{task?"Task":"Shopping item"}<Input name="title" aria-label={task?"Task name":"Shopping item name"} required maxLength={200} defaultValue={task?t?.title:s?.name} placeholder={task?"What needs to be done?":"What do you need?"}/></label>
 {task?<label className="block text-xs font-semibold">Due date<Input name="due_date" type="date" defaultValue={t?.due_date??""}/></label>:<><div className="grid grid-cols-3 gap-2"><label className="text-xs">Quantity<Input name="quantity" defaultValue={s?.quantity??""}/></label><label className="text-xs">Total cost ($)<Input name="total_cost" type="number" min="0" step="0.01" defaultValue={s?.total_cost??""}/></label><label className="text-xs">Paid ($)<Input name="paid_amount" type="number" min="0" step="0.01" defaultValue={s?.paid_amount??0}/></label></div><label className="block text-xs">Shopping link<Input name="url" type="url" placeholder="https://" defaultValue={s?.url??""}/></label></>}
 <div className="flex flex-wrap items-center gap-3"><label className="flex items-center gap-2 text-sm"><input name="done" type="checkbox" defaultChecked={task?t?.done:s?.purchased}/>{task?"Completed":"Purchased"}</label><Button size="sm" disabled={busy}>{row?"Save":"Add"}</Button>{row&&<Button type="button" size="sm" variant="ghost" disabled={busy} onClick={()=>{if(!confirm(`Delete this ${kind}?`))return;const fd=new FormData();fd.set("kind",kind);fd.set("id",row.id);fd.set("remove","1");void save(fd);}}>Delete</Button>}</div>{task&&t?.completed_at&&<p className="text-xs text-ink-500">Completed {new Date(t.completed_at).toLocaleDateString()}</p>}
 </form>}
 return <><Button type="button" size="sm" variant="secondary" className="mt-3" onClick={()=>{setMounted(true);setError("");void refresh().catch(()=>setError("Could not load your list. Please try again."));}}>Tasks & shopping</Button>{mounted&&createPortal(<dialog ref={node=>{dialog.current=node;if(node&&!node.open)node.showModal();}} onClose={()=>setMounted(false)} aria-label={`${label}: tasks and shopping`} className="m-auto max-h-[85dvh] w-[calc(100%_-_24px)] max-w-[720px] overflow-y-auto rounded-2xl bg-white p-5 shadow-xl backdrop:bg-black/40"><div className="mb-5 flex items-start justify-between gap-3"><div><h2 className="font-display text-2xl">{label}</h2><p className="text-sm text-ink-500">Tasks and shopping costs save directly to this event.</p></div><Button type="button" variant="ghost" onClick={()=>dialog.current?.close()}>Close</Button></div>{error&&<p role="alert" className="mb-3 text-rose-700">{error}</p>}<h3 className="mb-3 font-semibold">Tasks</h3><div className="space-y-3">{data.tasks.map(t=>entry("task",t))}{entry("task")}</div><h3 className="mb-3 mt-6 font-semibold">Shopping</h3><div className="space-y-3">{data.shopping.map(s=>entry("shopping",s))}{entry("shopping")}</div></dialog>,document.body)}</>;
}
