"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { VENUE_LOGISTICS_PLAN_ITEMS, type PlanChoice } from "@/lib/planning";
const VALID=new Set<PlanChoice>(["diy","hire","existing","undecided"]);
function refresh(id:string){revalidatePath(`/events/${id}`);revalidatePath(`/events/${id}/plan`);revalidatePath(`/events/${id}/venue-logistics`);revalidatePath(`/events/${id}/summary`);}
export async function saveVenueLogisticsPlan(eventId:string,fd:FormData){const s=createClient();const {data:old}=await s.from("event_plan_items").select("id,item_key").eq("event_id",eventId).eq("chapter","venue_logistics");const existing=new Map((old??[]).map(r=>[r.item_key,r]));const none=fd.get("no_venue_logistics")==="on";
if(none){const ids=(old??[]).map(r=>r.id);if(ids.length){await s.from("event_plan_item_photos").delete().in("plan_item_id",ids);await s.from("event_vendor_needs").delete().in("plan_item_id",ids).eq("status","needed");await s.from("event_plan_items").delete().in("id",ids);}await s.from("event_plan_items").upsert({event_id:eventId,chapter:"venue_logistics",item_key:"no_venue_logistics",label:"Nothing else to plan here",choice:"diy",vendor_category:null,notes:null,updated_at:new Date().toISOString()},{onConflict:"event_id,chapter,item_key"});refresh(eventId);if(String(fd.get("intent"))==="vendors")redirect(`/events/${eventId}/vendors`);if(String(fd.get("intent"))==="summary")redirect(`/events/${eventId}/summary`);redirect(`/events/${eventId}/venue-logistics?saved=1`);}
const sentinel=existing.get("no_venue_logistics");if(sentinel)await s.from("event_plan_items").delete().eq("id",sentinel.id);const selected=new Set<string>();for(const item of VENUE_LOGISTICS_PLAN_ITEMS){if(fd.get(`selected__${item.key}`)!=="on")continue;selected.add(item.key);let choice=String(fd.get(`choice__${item.key}`)??"undecided") as PlanChoice;if(!VALID.has(choice))choice="undecided";const custom=item.key==="other_rentals"?String(fd.get("custom_label__other_rentals")??"").trim():"";const label=custom||item.label;const notes=String(fd.get(`notes__${item.key}`)??"").trim()||null;const {data:row}=await s.from("event_plan_items").upsert({event_id:eventId,chapter:"venue_logistics",item_key:item.key,label,choice,vendor_category:item.vendorCategory,notes,updated_at:new Date().toISOString()},{onConflict:"event_id,chapter,item_key"}).select("id").single();if(!row)continue;if(choice==="hire"&&item.vendorCategory){await s.from("event_vendor_needs").upsert({event_id:eventId,plan_item_id:row.id,category:item.vendorCategory,label,notes,status:"needed",updated_at:new Date().toISOString()},{onConflict:"plan_item_id"});}else await s.from("event_vendor_needs").delete().eq("plan_item_id",row.id).eq("status","needed");}
const removed=[...existing.entries()].filter(([k])=>k!=="no_venue_logistics"&&!selected.has(k)).map(([,r])=>r.id);if(removed.length){await s.from("event_vendor_needs").delete().in("plan_item_id",removed).eq("status","needed");await s.from("event_plan_items").delete().in("id",removed);}refresh(eventId);if(String(fd.get("intent"))==="vendors")redirect(`/events/${eventId}/vendors`);if(String(fd.get("intent"))==="summary")redirect(`/events/${eventId}/summary`);redirect(`/events/${eventId}/venue-logistics?saved=1`);}
export async function uploadVenueLogisticsPhotos(eventId:string,planItemId:string|null,itemKey:string,fd:FormData):Promise<{error?:string;planItemId?:string;photos?:{id:string;url:string;sort:number}[]}>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return{error:"Please sign in again before uploading."};const def=VENUE_LOGISTICS_PLAN_ITEMS.find(x=>x.key===itemKey);if(!def)return{error:"That planning item could not be found."};let id=planItemId;if(!id){const {data:row,error}=await s.from("event_plan_items").upsert({event_id:eventId,chapter:"venue_logistics",item_key:def.key,label:def.label,choice:"undecided",vendor_category:def.vendorCategory,notes:null,updated_at:new Date().toISOString()},{onConflict:"event_id,chapter,item_key"}).select("id").single();if(error||!row)return{error:error?.message??"Could not prepare this item for photos."};id=row.id;}const files=fd.getAll("photos").filter((v):v is File=>v instanceof File&&v.size>0).slice(0,6);const {data:last}=await s.from("event_plan_item_photos").select("sort").eq("plan_item_id",id).order("sort",{ascending:false}).limit(1);let sort=(last?.[0]?.sort??-1)+1;const uploaded:{id:string;url:string;sort:number}[]=[];for(const file of files){if(!file.type.startsWith("image/"))continue;if(file.size>10_000_000)return{error:`${file.name} is larger than 10 MB.`};const ext=file.name.split(".").pop()?.toLowerCase()||"jpg";const path=`${user.id}/${eventId}/venue-logistics/${id}/${crypto.randomUUID()}.${ext}`;const {error}=await s.storage.from("event-inspiration").upload(path,file,{contentType:file.type,upsert:false});if(error)return{error:error.message};const {data:pub}=s.storage.from("event-inspiration").getPublicUrl(path);const currentSort=sort++;const {data:photo,error:insertError}=await s.from("event_plan_item_photos").insert({event_id:eventId,plan_item_id:id,url:pub.publicUrl,sort:currentSort}).select("id,url,sort").single();if(insertError||!photo)return{error:insertError?.message??"Could not save the uploaded photo."};uploaded.push(photo);}refresh(eventId);return{planItemId:id,photos:uploaded};}
export async function removeVenueLogisticsPhoto(eventId:string,planItemId:string,photoId:string){const s=createClient();await s.from("event_plan_item_photos").delete().eq("id",photoId).eq("event_id",eventId).eq("plan_item_id",planItemId);refresh(eventId);}
