import Link from "next/link";
import { notFound } from "next/navigation";
import { requireProfile } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { Button, Card, Badge, Progress } from "@/components/ui";
import { EventWorkspaceHeader } from "@/components/event/event-workspace-header";
import { ENTERTAINMENT_PLAN_ITEMS, type PlanChoice } from "@/lib/planning";
import { MusicIcon, CheckIcon, ChevronRightIcon } from "@/components/icons";
import { EntertainmentPhotoManager } from "@/components/event/entertainment-photo-manager";
import { saveEntertainmentPlan } from "./actions";
import { ChapterInteractions } from "@/components/event/chapter-interactions";

export default async function EntertainmentPage({params,searchParams}:{params:{id:string};searchParams?:{saved?:string}}){
 await requireProfile();const s=createClient();const {data:event}=await s.from("events").select("*").eq("id",params.id).single();if(!event)notFound();
 const [{data:rows},{data:needs},{data:itemPhotos}]=await Promise.all([s.from("event_plan_items").select("*").eq("event_id",params.id).eq("chapter","entertainment"),s.from("event_vendor_needs").select("id,label,category,status").eq("event_id",params.id).eq("status","needed"),s.from("event_plan_item_photos").select("id,plan_item_id,url,sort").eq("event_id",params.id).order("sort")]);
 const byKey=new Map((rows??[]).map(r=>[r.item_key,r]));const none=byKey.has("no_entertainment");const selected=(rows??[]).filter(r=>r.item_key!=="no_entertainment").length;const decided=(rows??[]).filter(r=>r.item_key!=="no_entertainment"&&r.choice!=="undecided").length;const progress=none?100:selected?Math.round(decided/selected*100):0;const photos=new Map<string,any[]>();for(const p of itemPhotos??[])photos.set(p.plan_item_id,[...(photos.get(p.plan_item_id)??[]),p]);const opts:[PlanChoice,string][]=[["hire","Hire"],["existing","I already have someone"],["undecided","Undecided"]];
 return <div className="space-y-7"><EventWorkspaceHeader event={event} active="/entertainment" eyebrow="My Party Plan · Entertainment"/><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="fleora-kicker">Chapter 5</p><h1 className="mt-1 font-display text-4xl text-ink-900">Plan the entertainment.</h1><p className="mt-2 max-w-2xl text-sm text-ink-600">Select only the entertainment you are considering. Fleora will expand those choices so you can plan, save inspiration and find the right vendors.</p></div><Link href={`/events/${event.id}/plan`} className="text-sm font-semibold text-plum-700 hover:underline">← Back to Party Plan</Link></div>
 {searchParams?.saved==="1"&&<Card className="border-sage-200 bg-sage-50/70"><p className="flex items-center gap-2 text-sm font-semibold text-ink-900"><CheckIcon size={16}/>Entertainment saved.</p></Card>}
 <Card variant="feature" className="bg-gradient-to-br from-plum-50 via-white to-blush-50"><div className="flex items-center justify-between gap-4"><div><p className="fleora-kicker">Chapter progress</p><p className="mt-1 font-display text-2xl text-ink-900">{none?"No entertainment needed":selected?`${decided} of ${selected} selected items decided`:"Choose what sounds right for your event"}</p></div><Badge tone={progress===100?"green":"plum"}>{progress}% planned</Badge></div><div className="mt-4"><Progress value={progress}/></div></Card>
 <form action={saveEntertainmentPlan.bind(null,event.id)} className="space-y-7"><ChapterInteractions skipName="no_entertainment" hasExistingData={(rows ?? []).some((r) => r.item_key !== "no_entertainment")}/><Card><label className="flex cursor-pointer items-start gap-3"><input type="checkbox" name="no_entertainment" defaultChecked={none} className="mt-1 h-5 w-5 rounded border-plum-300 text-plum-600"/><span><span className="block font-bold text-ink-900">No entertainment needed</span><span className="mt-1 block text-sm text-ink-500">My event does not need an entertainment vendor. Mark this chapter complete.</span></span></label></Card>
 <div className="grid gap-4 lg:grid-cols-2">{ENTERTAINMENT_PLAN_ITEMS.map(item=>{const row=byKey.get(item.key);const choice=((row?.choice==="diy"?"existing":row?.choice)??"undecided") as PlanChoice;return <Card key={item.key} variant="interactive"><label className="flex cursor-pointer items-start gap-3"><input type="checkbox" name={`selected__${item.key}`} defaultChecked={!!row} className="mt-1 h-5 w-5 rounded border-plum-300 text-plum-600"/><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-plum-50 text-plum-700"><MusicIcon size={19}/></span><span><span className="block font-display text-2xl text-ink-900">{item.label}</span><span className="mt-1 block text-sm text-ink-600">{item.description}</span></span></label><div data-plan-details-for={item.key} className="mt-5 border-t fleora-divider pt-4">{item.key==="other_custom_entertainment"&&<input name="custom_label__other_custom_entertainment" defaultValue={row?.label&&row.label!==item.label?row.label:""} placeholder="What entertainment do you need?" className="mb-3 w-full rounded-xl border border-plum-100 bg-white px-3 py-2.5 text-sm"/>}<p className="mb-2 text-xs font-bold uppercase tracking-wide text-ink-400">How are you handling it?</p><div className="grid gap-2 sm:grid-cols-3">{opts.map(([v,l])=><label key={v} className="flex cursor-pointer items-center gap-2 rounded-xl border border-plum-100 bg-white px-3 py-2.5 text-xs font-semibold"><input type="radio" name={`choice__${item.key}`} value={v} defaultChecked={choice===v}/>{v==="hire"?`Hire ${item.label.toLowerCase()}`:l}</label>)}</div><textarea name={`notes__${item.key}`} defaultValue={row?.notes??""} rows={2} placeholder="Optional notes…" className="mt-3 w-full rounded-xl border border-plum-100 bg-ivory-50/60 px-3 py-2.5 text-sm"/><EntertainmentPhotoManager eventId={event.id} planItemId={row?.id ?? null} itemKey={item.key} photos={row ? photos.get(row.id)??[] : []}/></div></Card>})}</div>
 {(needs??[]).length>0&&<Card variant="feature" className="border-plum-100 bg-plum-50/50"><p className="fleora-kicker">Vendor Needs</p><h2 className="mt-1 font-display text-2xl text-ink-900">Ready when you want to start searching.</h2><div className="mt-4 flex flex-wrap gap-2">{(needs??[]).map(n=><Link key={n.id} href={`/events/${event.id}/matches/${n.category}`} className="inline-flex items-center gap-1 rounded-full border border-plum-100 bg-white px-3 py-2 text-xs font-semibold text-plum-700 hover:bg-plum-50">{n.label}<ChevronRightIcon size={13}/></Link>)}</div></Card>}
 <Card variant="feature" className="sticky bottom-4 z-20 flex flex-wrap items-center justify-between gap-3 bg-white/95 backdrop-blur"><div><p className="text-sm font-bold">Save your entertainment plan.</p><p className="text-xs text-ink-500">Hire choices become Vendor Needs automatically.</p></div><div className="flex gap-2"><Button type="submit" name="intent" value="save" variant="secondary" size="lg">Save & stay</Button><Button type="submit" name="intent" value="continue" size="lg">Save & continue →</Button></div></Card></form></div>;
}
