import Link from "next/link";
import { notFound } from "next/navigation";
import { requireProfile } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { Button, Card, Badge, Progress } from "@/components/ui";
import { EventWorkspaceHeader } from "@/components/event/event-workspace-header";
import { SERVICE_PLAN_ITEMS, type PlanChoice } from "@/lib/planning";
import { CameraIcon, CheckIcon, ChevronRightIcon } from "@/components/icons";
import { ServicePhotoManager } from "@/components/event/service-photo-manager";
import { saveServicePlan } from "./actions";
import { ChapterInteractions } from "@/components/event/chapter-interactions";

export default async function ServicesPage({params,searchParams}:{params:{id:string};searchParams?:{saved?:string}}){
 await requireProfile(); const s=createClient();
 const {data:event}=await s.from("events").select("*").eq("id",params.id).single(); if(!event)notFound();
 const [{data:rows},{data:needs},{data:itemPhotos}]=await Promise.all([
  s.from("event_plan_items").select("*").eq("event_id",params.id).eq("chapter","services"),
  s.from("event_vendor_needs").select("id,label,category,status").eq("event_id",params.id).eq("status","needed"),
  s.from("event_plan_item_photos").select("id,plan_item_id,url,sort").eq("event_id",params.id).order("sort")
 ]);
 const byKey=new Map((rows??[]).map(r=>[r.item_key,r])); const noServices=byKey.has("no_services"); const selected=(rows??[]).filter(r=>r.item_key!=="no_services").length; const decided=(rows??[]).filter(r=>r.item_key!=="no_services"&&r.choice!=="undecided").length; const progress=noServices?100:selected?Math.round(decided/selected*100):0;
 const photos=new Map<string,any[]>(); for(const p of itemPhotos??[]) photos.set(p.plan_item_id,[...(photos.get(p.plan_item_id)??[]),p]);
 const opts:[PlanChoice,string][]=[["hire","Hire"],["diy","I already have someone"],["undecided","Undecided"]];
 return <div className="space-y-7">
  <EventWorkspaceHeader event={event} active="/services" eyebrow="My Party Plan · Services"/>
  <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="fleora-kicker">Chapter 4</p><h1 className="mt-1 font-display text-4xl text-ink-900">Plan your event services.</h1><p className="mt-2 max-w-2xl text-sm text-ink-600">Choose the professionals you need, note anyone you already have, and save the details Fleora can use when you are ready to reach out.</p></div><Link href={`/events/${event.id}/plan`} className="text-sm font-semibold text-plum-700 hover:underline">← Back to Party Plan</Link></div>
  {searchParams?.saved==="1"&&<Card className="border-sage-200 bg-sage-50/70"><p className="flex items-center gap-2 text-sm font-semibold text-ink-900"><CheckIcon size={16}/>Services saved.</p></Card>}
  <Card variant="feature" className="bg-gradient-to-br from-plum-50 via-white to-blush-50"><div className="flex items-center justify-between gap-4"><div><p className="fleora-kicker">Chapter progress</p><p className="mt-1 font-display text-2xl text-ink-900">{selected?`${decided} of ${selected} selected services decided`:"Choose what your event needs"}</p></div><Badge tone={progress===100&&selected?"green":"plum"}>{progress}% planned</Badge></div><div className="mt-4"><Progress value={progress}/></div></Card>
  <form action={saveServicePlan.bind(null,event.id)} className="space-y-7"><ChapterInteractions skipName="no_services" hasExistingData={(rows ?? []).some((r) => r.item_key !== "no_services")}/><Card><label className="flex cursor-pointer items-start gap-3"><input type="checkbox" name="no_services" defaultChecked={noServices} className="mt-1 h-5 w-5 rounded border-plum-300 text-plum-600"/><span><span className="block font-bold text-ink-900">No additional services needed</span><span className="mt-1 block text-sm text-ink-500">Mark Services complete without adding anything else.</span></span></label></Card>
   <div className="grid gap-4 lg:grid-cols-2">{SERVICE_PLAN_ITEMS.map(item=>{const row=byKey.get(item.key);const choice=(row?.choice??"undecided") as PlanChoice;return <Card key={item.key} variant="interactive"><label className="flex cursor-pointer items-start gap-3"><input type="checkbox" name={`selected__${item.key}`} defaultChecked={!!row} className="mt-1 h-5 w-5 rounded border-plum-300 text-plum-600"/><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-plum-50 text-plum-700"><CameraIcon size={19}/></span><span><span className="block font-display text-2xl text-ink-900">{item.label}</span><span className="mt-1 block text-sm text-ink-600">{item.description}</span></span></label><div data-plan-details-for={item.key} className="mt-5 border-t fleora-divider pt-4">{item.key==="other_custom_service"&&<input name="custom_label__other_custom_service" defaultValue={row?.label&&row.label!==item.label?row.label:""} placeholder="What service do you need?" className="mb-3 w-full rounded-xl border border-plum-100 bg-white px-3 py-2.5 text-sm"/>}<p className="mb-2 text-xs font-bold uppercase tracking-wide text-ink-400">Choose an option</p><div className="grid gap-2 sm:grid-cols-3">{opts.map(([v,l])=><label key={v} className="flex cursor-pointer items-center gap-2 rounded-xl border border-plum-100 bg-white px-3 py-2.5 text-xs font-semibold"><input type="radio" name={`choice__${item.key}`} value={v} defaultChecked={choice===v}/>{v==="hire"?item.key==="event_planner"?"Hire a planner / coordinator":item.key==="event_staff"?"Hire staff / servers":item.key==="hair"?"Hire a hair stylist":item.key==="makeup"?"Hire a makeup artist":item.key==="photographer"?"Hire a photographer":item.key==="videographer"?"Hire a videographer":item.key==="photobooth"?"Hire a photo booth":item.key==="other_custom_service"?"Hire someone":l:l}</label>)}</div><textarea name={`notes__${item.key}`} defaultValue={row?.notes??""} rows={2} placeholder="Optional notes…" className="mt-3 w-full rounded-xl border border-plum-100 bg-ivory-50/60 px-3 py-2.5 text-sm"/>{row?<ServicePhotoManager eventId={event.id} planItemId={row.id} photos={photos.get(row.id)??[]}/>:null}</div></Card>})}</div>
   {(needs??[]).length>0&&<Card variant="feature" className="border-plum-100 bg-plum-50/50"><p className="fleora-kicker">Vendor Needs</p><h2 className="mt-1 font-display text-2xl text-ink-900">Ready when you want to start searching.</h2><div className="mt-4 flex flex-wrap gap-2">{(needs??[]).map(n=><Link key={n.id} href={`/events/${event.id}/matches/${n.category}`} className="inline-flex items-center gap-1 rounded-full border border-plum-100 bg-white px-3 py-2 text-xs font-semibold text-plum-700 hover:bg-plum-50">{n.label}<ChevronRightIcon size={13}/></Link>)}</div></Card>}
   <Card variant="feature" className="sticky bottom-4 z-20 flex flex-wrap items-center justify-between gap-3 bg-white/95 backdrop-blur"><div><p className="text-sm font-bold">Save your services as you go.</p><p className="text-xs text-ink-500">Hiring choices become Vendor Needs automatically.</p></div><div className="flex gap-2"><Button type="submit" name="intent" value="save" variant="secondary" size="lg">Save & stay</Button><Button type="submit" name="intent" value="continue" size="lg">Save & continue →</Button></div></Card>
  </form>
 </div>;
}
